// Generated by ts-to-zod
import { z } from "zod";

const tagNameSchema = z.string();

const urlSchema = z.string();

const artistNameSchema = z.string();

const mbidSchema = z.string();

const durationSchema = z.string();

const nameSchema = z.string();

const publishedSchema = z.string();

const summarySchema = z.string();

const contentSchema = z.string();

const playcountSchema = z.string();

const imageSchema = z.string();

const albumNameSchema = z.string();

const listenersSchema = z.string();

const userNameSchema = z.string();

const langSchema = z.string();

const countSchema = z.union([z.string(), z.number()]);

const limitSchema = z.union([z.string(), z.number()]);

const pageSchema = z.string();

const textSchema = z.string();

const roleSchema = z.string();

const searchTermsSchema = z.string();

const startPageSchema = z.string();

const totalResultsSchema = z.string();

const startIndexSchema = z.string();

const itemsPerPageSchema = z.string();

const forSchema = z.string();

const albumTagSchema = z.object({
    tag: z.union([z.array(z.object({
            name: tagNameSchema,
            url: urlSchema
        })), z.object({
            name: tagNameSchema,
            url: urlSchema
        })]).optional()
});

const albumTrackArtistSchema = z.object({
    name: artistNameSchema,
    mbid: mbidSchema,
    url: urlSchema
});

const albumTrackSchema = z.object({
    track: z.array(z.object({
        duration: durationSchema,
        name: nameSchema,
        url: urlSchema,
        artist: albumTrackArtistSchema
    }))
});

const albumWikiSchema = z.object({
    published: publishedSchema,
    summary: summarySchema,
    content: contentSchema
});

/**
 * Album
 * @see https://www.last.fm/api/show/album.getInfo
 */
export const albumSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema,
    tags: albumTagSchema,
    playcount: playcountSchema,
    image: z.array(imageSchema),
    tracks: albumTrackSchema.optional(),
    url: urlSchema,
    name: albumNameSchema,
    listeners: listenersSchema,
    wiki: albumWikiSchema,
    userplaycount: playcountSchema.optional()
});

export const albumGetInfoRequestSchema = z.object({
    artist: artistNameSchema,
    album: albumNameSchema,
    mbid: mbidSchema.optional(),
    username: userNameSchema.optional(),
    lang: langSchema.optional()
});

export const albumGetInfoResponseSchema = z.object({
    album: albumSchema
});

export const albumGetTagsRequestSchema = z.object({
    artist: artistNameSchema,
    album: albumNameSchema,
    mbid: mbidSchema.optional(),
    user: userNameSchema
});

export const albumGetTagsResponseSchema = z.object({
    tags: z.object({
        tag: z.array(z.object({
            name: tagNameSchema,
            url: urlSchema
        }))
    }),
    "@attr": z.object({
        album: albumNameSchema,
        artist: artistNameSchema
    })
});

export const albumGetTopTagsRequestSchema = z.object({
    artist: artistNameSchema,
    album: albumNameSchema,
    mbid: mbidSchema.optional()
});

export const albumGetTopTagsResponseSchema = z.object({
    tags: z.object({
        tag: z.array(z.object({
            name: tagNameSchema,
            url: urlSchema,
            count: countSchema
        }))
    }),
    "@attr": z.object({
        album: albumNameSchema,
        artist: artistNameSchema
    })
});

export const albumSearchRequestSchema = z.object({
    album: albumNameSchema,
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const albumSearchResponseSchema = z.object({
    results: z.object({
        "opensearch:Query": z.object({
            "#text": textSchema,
            role: roleSchema,
            searchTerms: searchTermsSchema,
            startPage: startPageSchema
        }),
        "opensearch:totalResults": totalResultsSchema,
        "opensearch:startIndex": startIndexSchema,
        "opensearch:itemsPerPage": itemsPerPageSchema,
        albummatches: z.object({
            album: z.array(z.object({
                name: albumNameSchema,
                artist: artistNameSchema,
                url: urlSchema,
                image: z.array(imageSchema),
                mbid: mbidSchema
            }))
        }),
        "@attr": z.object({
            for: forSchema
        })
    })
});
