// Generated by ts-to-zod
import { z } from "zod";

const listenersSchema = z.string();

const playcountSchema = z.string();

const artistNameSchema = z.string();

const urlSchema = z.string();

const imageSchema = z.string();

const tagNameSchema = z.string();

const textSchema = z.string();

const publishedSchema = z.string();

const summarySchema = z.string();

const contentSchema = z.string();

const mbidSchema = z.string();

const langSchema = z.string();

const userNameSchema = z.string();

const limitSchema = z.union([z.string(), z.number()]);

const matchSchema = z.string();

const pageSchema = z.string();

const itemsPerPageSchema = z.string();

const totalPagesSchema = z.string();

const totalSchema = z.union([z.string(), z.number()]);

const countSchema = z.union([z.string(), z.number()]);

const rankSchema = z.string();

const roleSchema = z.string();

const searchTermsSchema = z.string();

const startPageSchema = z.string();

const totalResultsSchema = z.string();

const startIndexSchema = z.string();

const forSchema = z.string();

export const artistStatsSchema = z.object({
    listeners: listenersSchema,
    playcount: playcountSchema,
    userplaycount: playcountSchema.optional()
});

export const artistSimilarSchema = z.object({
    artist: z.array(z.object({
        name: artistNameSchema,
        url: urlSchema,
        image: z.array(imageSchema)
    }))
});

export const artistTagsSchema = z.object({
    tag: z.array(z.object({
        name: tagNameSchema,
        url: urlSchema
    }))
});

export const artistBioSchema = z.object({
    links: z.object({
        link: z.object({
            "#text": textSchema,
            rel: z.string(),
            href: z.string()
        })
    }),
    published: publishedSchema,
    summary: summarySchema,
    content: contentSchema
});

/**
 * Artist
 * @see https://www.last.fm/api/show/artist.getInfo
 */
export const artistSchema = z.object({
    name: artistNameSchema,
    mbid: mbidSchema,
    url: urlSchema,
    image: z.array(imageSchema),
    ontour: z.string(),
    stats: artistStatsSchema,
    similar: artistSimilarSchema,
    tags: artistTagsSchema,
    bio: artistBioSchema
});

export const artistGetInfoRequestSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema.optional(),
    lang: langSchema.optional(),
    user: userNameSchema.optional()
});

export const artistGetInfoResponseSchema = z.object({
    artist: artistSchema
});

export const artistGetTagsRequestSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema.optional(),
    limit: limitSchema.optional()
});

export const artistGetTagsResponseSchema = z.object({
    tags: z.object({
        tag: z.array(z.object({
            name: tagNameSchema,
            url: urlSchema
        })),
        "@attr": z.object({
            artist: artistNameSchema
        })
    })
});

export const artistGetSimilarRequestSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema.optional(),
    limit: limitSchema.optional()
});

export const artistGetSimilarResponseSchema = z.object({
    similarartists: z.object({
        artist: z.array(z.object({
            name: artistNameSchema,
            match: matchSchema,
            url: urlSchema,
            image: z.array(imageSchema)
        })),
        "@attr": z.object({
            artist: artistNameSchema
        })
    })
});

export const artistGetTopAlbumsRequestSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema.optional(),
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const artistGetTopAlbumsResponseSchema = z.object({
    topalbums: z.object({
        album: z.array(z.object({
            name: artistNameSchema,
            playcount: playcountSchema,
            mbid: mbidSchema,
            url: urlSchema,
            artist: z.object({
                name: artistNameSchema,
                mbid: mbidSchema,
                url: urlSchema
            }),
            image: z.array(imageSchema)
        })),
        "@attr": z.object({
            artist: artistNameSchema,
            page: pageSchema,
            perPage: itemsPerPageSchema,
            totalPages: totalPagesSchema,
            total: totalSchema
        })
    })
});

export const artistGetTopTagsRequestSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema.optional()
});

export const artistGetTopTagsResponseSchema = z.object({
    toptags: z.object({
        tag: z.array(z.object({
            name: tagNameSchema,
            url: urlSchema,
            count: countSchema
        })),
        "@attr": z.object({
            artist: artistNameSchema
        })
    })
});

export const artistGetTopTracksRequestSchema = z.object({
    artist: artistNameSchema,
    mbid: mbidSchema.optional(),
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const artistGetTopTracksResponseSchema = z.object({
    toptracks: z.object({
        track: z.array(z.object({
            name: artistNameSchema,
            playcount: playcountSchema,
            listeners: listenersSchema,
            mbid: mbidSchema,
            url: urlSchema,
            artist: z.object({
                name: artistNameSchema,
                mbid: mbidSchema,
                url: urlSchema
            }),
            image: z.array(imageSchema),
            "@attr": z.object({
                rank: rankSchema
            })
        })),
        "@attr": z.object({
            artist: artistNameSchema,
            page: pageSchema,
            perPage: itemsPerPageSchema,
            totalPages: totalPagesSchema,
            total: totalSchema
        })
    })
});

export const artistSearchRequestSchema = z.object({
    artist: artistNameSchema,
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const artistSearchResponseSchema = z.object({
    results: z.object({
        "opensearch:Query": z.object({
            "#text": textSchema,
            role: roleSchema,
            searchTerms: searchTermsSchema,
            startPage: startPageSchema
        }),
        "opensearch:totalResults": totalResultsSchema,
        "opensearch:startIndex": startIndexSchema,
        "opensearch:itemsPerPage": itemsPerPageSchema,
        artistmatches: z.object({
            artist: z.array(z.object({
                name: artistNameSchema,
                listeners: listenersSchema,
                mbid: mbidSchema,
                url: urlSchema,
                image: z.array(imageSchema)
            }))
        }),
        "@attr": z.object({
            for: forSchema
        })
    })
});
