// Generated by ts-to-zod
import { z } from "zod";

const countrySchema = z.string();

const limitSchema = z.union([z.string(), z.number()]);

const pageSchema = z.string();

const artistNameSchema = z.string();

const listenersSchema = z.string();

const mbidSchema = z.string();

const urlSchema = z.string();

const imageSchema = z.string();

const itemsPerPageSchema = z.string();

const totalPagesSchema = z.string();

const totalSchema = z.union([z.string(), z.number()]);

const locSchema = z.string();

const trackNameSchema = z.string();

const durationSchema = z.string();

const rankSchema = z.string();

export const geoGetTopArtistsRequestSchema = z.object({
    country: countrySchema,
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const geoGetTopArtistsResponseSchema = z.object({
    topartists: z.object({
        artist: z.array(z.object({
            name: artistNameSchema,
            listeners: listenersSchema,
            mbid: mbidSchema,
            url: urlSchema,
            image: z.array(imageSchema)
        })),
        "@attr": z.object({
            country: countrySchema,
            page: pageSchema,
            perPage: itemsPerPageSchema,
            totalPages: totalPagesSchema,
            total: totalSchema
        })
    })
});

export const geoGetTopTracksRequestSchema = z.object({
    country: countrySchema,
    location: locSchema.optional(),
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const geoGetTopTracksResponseSchema = z.object({
    tracks: z.object({
        track: z.array(z.object({
            name: trackNameSchema,
            duration: durationSchema,
            listeners: listenersSchema,
            mbid: mbidSchema,
            url: urlSchema,
            artist: z.object({
                name: artistNameSchema,
                mbid: mbidSchema,
                url: urlSchema
            }),
            image: z.array(imageSchema),
            "@attr": z.object({
                rank: rankSchema
            })
        })),
        "@attr": z.object({
            country: countrySchema,
            page: pageSchema,
            perPage: itemsPerPageSchema,
            totalPages: totalPagesSchema,
            total: totalSchema
        })
    })
});
