// Generated by ts-to-zod
import { z } from "zod";

const userNameSchema = z.string();

const limitSchema = z.union([z.string(), z.number()]);

const pageSchema = z.string();

const countSchema = z.union([z.string(), z.number()]);

const imageSchema = z.string();

const mbidSchema = z.string();

const urlSchema = z.string();

const playcountSchema = z.string();

const artistNameSchema = z.string();

const totalPagesSchema = z.string();

const itemsPerPageSchema = z.string();

const totalSchema = z.union([z.string(), z.number()]);

export const libraryGetArtistsRequestSchema = z.object({
    user: userNameSchema,
    limit: limitSchema.optional(),
    page: pageSchema.optional()
});

export const libraryGetArtistsResponseSchema = z.object({
    artists: z.object({
        artist: z.array(z.object({
            tagCount: countSchema,
            image: z.array(imageSchema),
            mbid: mbidSchema,
            url: urlSchema,
            playcount: playcountSchema,
            name: artistNameSchema
        })),
        "@attr": z.object({
            user: userNameSchema,
            totalPages: totalPagesSchema,
            page: pageSchema,
            perPage: itemsPerPageSchema,
            total: totalSchema
        })
    })
});
