export const method = {
  auth: {
    getMobileSession: "auth.getMobileSession",
    getSession: "auth.getSession",
    getToken: "auth.getToken",
  },
  user: {
    getFriends: "user.getFriends",
    getInfo: "user.getInfo",
    getLovedTracks: "user.getLovedTracks",
    getPersonalTags: "user.getPersonalTags",
    getRecentTracks: "user.getRecentTracks",
    getTopAlbums: "user.getTopAlbums",
    getTopArtists: "user.getTopArtists",
    getTopTags: "user.getTopTags",
    getTopTracks: "user.getTopTracks",
    getWeeklyAlbumChart: "user.getWeeklyAlbumChart",
    getWeeklyArtistChart: "user.getWeeklyArtistChart",
    getWeeklyChartList: "user.getWeeklyChartList",
    getWeeklyTrackChart: "user.getWeeklyTrackChart",
  },
  track: {
    addTags: "track.addTags",
    getCorrection: "track.getCorrection",
    getInfo: "track.getInfo",
    getSimilar: "track.getSimilar",
    getTags: "track.getTags",
    getTopTags: "track.getTopTags",
    love: "track.love",
    removeTag: "track.removeTag",
    scrobble: "track.scrobble",
    search: "track.search",
    unlove: "track.unlove",
    updateNowPlaying: "track.updateNowPlaying",
  },
  album: {
    addTags: "album.addTags",
    getInfo: "album.getInfo",
    getTags: "album.getTags",
    removeTag: "album.removeTag",
    search: "album.search",
  },
  artist: {
    addTags: "artist.addTags",
    getCorrection: "artist.getCorrection",
    getInfo: "artist.getInfo",
    getTags: "artist.getTags",
    getTopAlbums: "artist.getTopAlbums",
    getTopTags: "artist.getTopTags",
    getTopTracks: "artist.getTopTracks",
    removeTag: "artist.removeTag",
    search: "artist.search",
  },
  library: {},
  tag: {
    getInfo: "tag.getInfo",
    getTopArtists: "tag.getTopArtists",
    getTopTracks: "tag.getTopTracks",
    getTopAlbums: "tag.getTopAlbums",
    getTopTags: "tag.getTopTags",
    getSimilar: "tag.getSimilar",
    getWeeklyChartList: "tag.getWeeklyChartList",
  },
  chart: {
    getTopArtists: "chart.getTopArtists",
    getTopTags: "chart.getTopTags",
    getTopTracks: "chart.getTopTracks",
  },
  geo: {
    getTopArtists: "geo.getTopArtists",
    getTopTracks: "geo.getTopTracks",
  },
};
